# .github/workflows/main.yml
name: Run Local Action

on:
  workflow_dispatch:

jobs:
  use-local-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # - name: Run custom local action
      #   uses: ./.github/actions/my-action
