name: OS-Specific Runner Demo

on:
  # workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  run-on-linux:
    name: Run on Ubuntu
    runs-on: self-hosted
    steps:
      - name: Echo Linux
        run: echo "Running on Linux1"

  run-on-windows:
    name: Run on Windows
    runs-on: windows-latest
    steps:
      - name: Echo Windows
        run: echo "Running on Windows"

