name: Download Artifact

on: [workflow_dispatch]

jobs:
  download-and-use:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: downloaded/

      - name: Show file content
        run: cat downloaded/message.txt
