name: pushing images to ecr repository in AWS

on: 
  workflow_dispatch:

jobs:
  ecr-repo:
    runs-on: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          echo "Files in the repository:"
          ls -la
          echo "Files in Docker context directory:"
          ls -la workflows/torch/hack/docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t0x7f1q9

      - name: Build the Docker image
        run: |
          docker build -t lakshman/test-repo -f workflows/torch/hack/docker/Dockerfile.sagemaker workflows/torch/hack/docker

      - name: Tag the Docker image
        run: |
          docker tag lakshman/test-repo:latest public.ecr.aws/t0x7f1q9/lakshman/test-repo:latest

      - name: Push the Docker image to ECR
        run: |
          docker push public.ecr.aws/t0x7f1q9/lakshman/test-repo:latest
