name: pushing images to ecr repository in AWS

on: 
  workflow_dispatch:

jobs:
  ecr-repo:
    runs-on: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List Dockerfiles
        run: |
          echo "Available Dockerfiles:"
          ls -l .github/workflows/torch/hack/docker/Dockerfile.*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t0x7f1q9

      - name: Build, tag, and push Docker images dynamically
        run: |
          for file in .github/workflows/torch/hack/docker/Dockerfile.*; do
            echo "Processing Dockerfile: $file"

            # Extract tag from filename (e.g., Dockerfile.sagemaker → sagemaker)
            TAG=$(basename "$file" | cut -d'.' -f2-)

            # Define image name
            IMAGE_NAME=lakshman/test-repo:$TAG
            ECR_IMAGE=public.ecr.aws/t0x7f1q9/$IMAGE_NAME

            echo "Building image: $IMAGE_NAME"
            docker build -t $IMAGE_NAME -f "$file" .github/workflows/torch/hack/docker

            echo "Tagging image as: $ECR_IMAGE"
            docker tag $IMAGE_NAME $ECR_IMAGE

            echo "Pushing image: $ECR_IMAGE"
            docker push $ECR_IMAGE
          done
