name: pushing images to ecr repository in AWS

on: workflow_dispatch

jobs:
    ecr-repo:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1
            
            - name: Login to Amazon ECR
              run: |
                aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/t0x7f1q9
            
            - name: Build the docker image
              run: |
                docker build -t lakshman/test-repo .

            - name: Tag the docker image
              run: |
                docker tag lakshman/test-repo:latest public.ecr.aws/t0x7f1q9/lakshman/test-repo:latest
                
            - name: Push the docker image to ECR
              run: |    
                docker push public.ecr.aws/t0x7f1q9/lakshman/test-repo:latest


