name: My-First-Job

on: workflow_dispatch
    # push


jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: My first github job
              run: |
                echo "Welcome to github actions"
                ls -la
                cat README.md


            # - name: List all the files
            #   run: ls -la

            # - name: Read the file
            #   run: cat README.md

