name: Hosting httpd server

on: #push

    workflow_dispatch

jobs:
    httpd-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Apache HTTP Server
              run: |
                sudo apt-get update
                sudo apt-get install -y apache2
                sudo systemctl start apache2
                sudo systemctl enable apache2
                echo "Apache HTTP Server installed and started."

            - name: Configure Apache HTTP Server
              run: |
                chmod -R 755 /var/www/html/index.html
                ls -la /var/www/html
                rm -rf sudo /var/www/html/index.html
                echo "<html><body><h1>Welcome to the Apache HTTP Server!</h1></body></html>" | sudo tee /var/www/html/index.html
            
            - name: access the server
              run: |
                echo "Access the server at http://localhost:80"
                sleep 5  # Wait for a few seconds to ensure the server is up
                curl http://localhost:80 || echo "Failed to access the server"

