name: Printing github env secrets.

on: 
    #workflow_dispatch:
    push

jobs:
    github-env-secrets:
        runs-on: ubuntu-latest
        #environment: NAME
        steps:
            - name: Print variables from github environment variables.
              run: |
                echo "My PAssword is: ${{ secrets.BAT_1 }}"


