name: Upload Artifact

on: [workflow_dispatch]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact file
        run: |
          mkdir -p output
          echo "✅ Hello from GitHub Actions!" > output/message.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/
